services:
  db:
    image: postgres:13.22
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER:-playnite}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped

  mqtt:
    image: eclipse-mosquitto:2.0.18
    ports:
      - '1883:1883'
      - '9001:9001'
    volumes:
      - mqtt_config:/mosquitto/config
    restart: unless-stopped

  playnite-web:
    image: ghcr.io/andrew-codes/playnite-web-app:latest
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      - PORT=3000
      - HOST=${APP_HOST:-localhost}
      - DATABASE_URL=postgres://${DB_USER:-playnite}:${DB_PASSWORD}@db:5432?schema=public
      - SECRET=${APP_SECRET}
      - DISABLE_CSP=${DISABLE_CSP:-false}
      - CSP_ORIGINS=${CSP_ORIGINS}
      - ADDITIONAL_ORIGINS=${ADDITIONAL_ORIGINS}
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
    volumes:
      - games_assets:/opt/playnite-web-app/public/assets/game-assets
    depends_on:
      - db
      - mqtt
    restart: unless-stopped

  playnite-web-game-asssets-processor:
    image: ghcr.io/andrew-codes/playnite-web-game-assets-processor:latest
    ports:
      - '${PROCESSOR_PORT:-3001}:3000'
    environment:
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - MQTT_USERNAME=${MQTT_USERNAME}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - DATABASE_URL=postgres://${DB_USER:-playnite}:${DB_PASSWORD}@db:5432?schema=public
      - PORT=3000
    volumes:
      - games_assets:/opt/playnite-web/game-assets
    depends_on:
      - playnite-web
    restart: unless-stopped

volumes:
  games_assets:
  mqtt_config:
